### ISSUE TITLE
The Saas workshop instruction webpage not working anymore

### ISSUE THREAD

**Issue by Taitanguo** [aws-samples/aws-serverless-saas-workshop#2]
https://catalog.us-east-1.prod.workshops.aws/v2/workshops/b0c6ad36-0a4b-45d8-856b-8a64f0ac76bb/en-US

Please refer the link above

**Comment by ujwalbukka** [comment]
The above mentioned documentation link is working. Will close this issue, please re-open it if you still have any issues.
