### ISSUE TITLE
XRay tracing of Annotation.TenantId not available

### ISSUE THREAD

**Issue by lspellman** [aws-samples/aws-serverless-saas-workshop#4]
Context: Lab3, Multi-tenant observability, tenant-aware tracing using X-Ray

Indicates that there should be a Group By option for Annotation.TenantId. It's not in the list. There are 4 options available for Annotation:
* aws:api_id
* aws:api_stage
* ColdStart
* Service

I checked the stack-pooled-CreateProduct function and exported to checked it to make sure annotation code is present, and it is:
```
@tracer.capture_lambda_handler
def create_product(event, context):    
    tenantId = event['requestContext']['authorizer']['tenantId']
    tracer.put_annotation(key="TenantId", value=tenantId)
```

I'm sure this is something I've done wrong in configuration / following instructions, but not sure what it is. Thanks for any pointers.

**Comment by anubhavynr** [comment]
replied on the other issue. This one is duplicate
