### ISSUE TITLE
Can't onboard tenant

### ISSUE THREAD

**Issue by hosamshahin** [aws-samples/aws-serverless-saas-workshop#42]
When onboarding a tenant from the admin or the registration app I got the following error:

Access to XMLHttpRequest at 'https://000.execute-api.us-east-1.amazonaws.com/prod//registration' from origin 'https://000.cloudfront.net' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by metarama** [comment]
I am seeing this error. How did you fix it?
