### ISSUE TITLE
CORS error

### ISSUE THREAD

**Issue by metarama** [aws-samples/aws-serverless-saas-workshop#43]
When onboarding a tenant from the admin or the registration app I got the following error:

Access to XMLHttpRequest at 'https://000.execute-api.us-east-1.amazonaws.com/prod//registration' from origin 'https://000.cloudfront.net/' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by ujwalbukka** [comment]
Hi @metarama 

In which Lab your are getting this error?  And also what error do you see in RegisterTenant lambda function?

**Comment by metarama** [comment]
Hi Ujwal. Thanks for quick response. I deployed Lab2 WITHOUT completing the incomplete code. That could be the root cause. The CORS error I see on the Javascript Console in the browser when I try to register a new tenant. That message was confusing.

I ran the  scripts/cleanup.sh script. Now restarting the workshop. I will report back with my findings.
