### ISSUE TITLE
Question about Auth for Events/Queues

### ISSUE THREAD

**Issue by pedraohenrique** [aws-samples/aws-serverless-saas-workshop#46]
I'm using this bootstrap to build a new platform and I have a question for the Architects:

I need a Tentant/Pooled component that looks like this: Event Bridge -> Lambda -> SQS -> Lambda, which auth model I should use?

The solution described above will run once a day to process the billing task.

Thanks!

**Comment by metarama** [comment]
@pedraohenrique your use case is almost identical to the scenario in Lab 7 that runs the daily cost attribution.  Can you use an identical approach to implement your use case?

**Comment by pedraohenrique** [comment]
@metarama My case has a diference because it should run at Tenant Level with data partitioning, cost/user per Tenant...

> @pedraohenrique your use case is almost identical to the scenario in Lab 7 that runs the daily cost attribution. Can you use an identical approach to implement your use case?

**Comment by ujwalbukka** [comment]
Hi @pedraohenrique 

Can you elaborate on your requirement? are you trying to calculate cost per tenant for your architecture you mentioned above?

**Comment by pedraohenrique** [comment]
> Hi @pedraohenrique
> 
> Can you elaborate on your requirement? are you trying to calculate cost per tenant for your architecture you mentioned above?

No. This billing process is part of my Saas solution. It's a video on demand platform that feature subscription plans (just like Netflix). Each Tennant should be able to charge their users monthly.

**Comment by anubhavynr** [comment]
Hi @pedraohenrique - Usually billing process is part of your control plane. 

SaaS Boost provides you an example Billing Integration. Please see the link below:

https://github.com/awslabs/aws-saas-boost/blob/main/docs/developer-guide.md#billing-integration

If you need a deeper discussion, then please hit me up on linkedin and we can have a quick call.

**Comment by ujwalbukka** [comment]
Hi @pedraohenrique - Did you get the information you were looking for? need anything more?

**Comment by ujwalbukka** [comment]
Do you want to have a quick call and discuss this? you can reach out to us through linkedin?

**Comment by pedraohenrique** [comment]
Yes, I would!! I'll help us a lot!! How can I find you at Linkedin? This is
my profile: www.linkedin.com/in/pedro-henrique-corado-1827b666


Pedro Corado
AD Studio
Tel.: (61) 99904-9526


Em qui., 8 de dez. de 2022 às 15:54, Ujwal ***@***.***>
escreveu:

**Comment by ujwalbukka** [comment]
Discussed with @pedraohenrique and provided recommendations for his architecture challenges. Please reopen this issue if you have any more questions.
