### ISSUE TITLE
Need to Update Pre-requisites File

### ISSUE THREAD

**Issue by bdmostafa** [aws-samples/aws-serverless-saas-workshop#48]
The minimum required version of `AWS SDK` is `2.40.0` right now which is shown while checking `pre-requisites-versions` but `2.0.0` is used in `pre-requisites.sh` file under the `Cloud9Setup` folder. Even though it will update the package to all future minor/patch versions, without incrementing the major version because of using Caret `(^)` here, it's far better to use the minimum required version.

**Comment by anubhavynr** [comment]
Thanks for the pull request. We will look into this post reInvent.

**Comment by ujwalbukka** [comment]
Merged the pull request. Thanks for the pull request.
