### ISSUE TITLE
X-Ray Group By Annotation.TenantId not available

### ISSUE THREAD

**Issue by lspellman** [aws-samples/aws-serverless-saas-workshop#5]
Context: Lab3, Multi-tenant observability, tenant-aware tracing using X-Ray

Indicates that there should be a Group By option for Annotation.TenantId. It's not in the list. There are 4 options available for Annotation:
* aws:api_id
* aws:api_stage
* ColdStart
* Service

I checked the stack-pooled-CreateProduct function and exported to checked it to make sure annotation code is present, and it is:
```
@tracer.capture_lambda_handler
def create_product(event, context):    
    tenantId = event['requestContext']['authorizer']['tenantId']
    tracer.put_annotation(key="TenantId", value=tenantId)
```

I'm sure this is something I've done wrong in configuration / following instructions, but not sure what it is. Thanks for any pointers.

**Comment by anubhavynr** [comment]
hi @lspellman did you exercised the application and interested some data into the application, using the service? The annotation won't show up otherwise by default.

Please let me know if you already tried that.

**Comment by lspellman** [comment]
Yes, sorry, should have stated that more clearly. After having run the lambda, then going to X-Ray, the bulleted items above were the only Annotation types that were available for filtering. It appears that it didn't capture the TenantId Annotation.

**Comment by ujwalbukka** [comment]
hi @lspellman in the X-Ray, "Annotation.TenantId" is getting captured but in the "Group by" drop down it is getting placed as a last item and it is not visible in the drop down directly. 
Please use the down arrow to navigate the elements in the "Group by" drop down once you are at the last item(which won't be visible) just hit enter and you should see "Annotation.TenantId" selected. I was able to replicate and check this on my end.

You can also look at this similar data under CloudWatch --> X-Ray traces --> Traces. Under "Query refiners" you will have a "Refine query by" drop down where you can select the user annotations like "TenantId".

**Comment by ujwalbukka** [comment]
Closing this issue. Please re-open if you still have issues.
