### ISSUE TITLE
Tenant Pipeline Updates to Python 3.9 cause issue with lambda to deploytenantstack

### ISSUE THREAD

**Issue by tvanceadv** [aws-samples/aws-serverless-saas-workshop#55]
serverless-saas-pipeline-deploytenantstack is still leveraging the Python3.8.  Runtime and Lambda application still reflect Python 3.8.  I will submit a pull request to correct the issue.

**Comment by suhussai** [comment]
PR #56 merged! Thanks @tvanceadv !
