### ISSUE TITLE
Product List is not accessible in Lab3 

### ISSUE THREAD

**Issue by cscetbon** [aws-samples/aws-serverless-saas-workshop#60]
I've followed the workshop of Lab3, however when trying to list products I see a spinning wheel and the javascript console prints out
```
XMLHttpRequest cannot load https://my-api-id.execute-api.us-west-2.amazonaws.com/prod/products due to access control checks.

[Error] Failed to load resource: Origin https://my-cloudfront-id.cloudfront.net is not allowed by Access-Control-Allow-Origin. Status code: 502 (products, line 0)
```
In CLoudWatch logs I can see that the authorizer works as expected and here is the policy it builds

```
{
        "principalId": "78d1a300-1021-70e2-386a-b24d910d09c2",
        "policyDocument": {
            "Version": "2012-10-17",
            "Statement": [
                {
                    "Action": "execute-api:Invoke",
                    "Effect": "Allow",
                    "Resource": [
                        "arn:aws:execute-api:us-west-2:469517728181:my-api-id/prod/*/*"
                    ]
                }
            ]
        }
    }
```

It's definitely what it does at https://github.com/aws-samples/aws-serverless-saas-workshop/blob/main/Lab3/server/Resources/tenant_authorizer.py#L164-L170 and it looks perfectly okay with what [AWS doc ](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-control-access-using-iam-policies-to-invoke-api.html)explains.

Any idea what's going on here ?

**Comment by cscetbon** [comment]
Deploying Lab4 fixes it so it's definitely happening before

**Comment by ujwalbukka** [comment]
@cscetbon Thanks for reporting this, we will try to reproduce on our end and get back to you.

**Comment by ujwalbukka** [comment]
@cscetbon - We have tried to replicate this error, but in Lab3 while listing products we did not encountered this error.

Can you check if you can find any errors related to his in the cloudwatch logs of tenant_authorizer and/or "pooled-serverless-saas-tenant-api" API Gateway execution logs? if not, can you please try to replicate it.

**Comment by cscetbon** [comment]
Weird, not sure when I'll be able to try it again as I progressed to lab7. It could have been a problem when running sequentially the workshop. Then let's close it for now and I'll reopen it if I meet it again
