### ISSUE TITLE
[Question] API Gateway/Proxy/SAAS

### ISSUE THREAD

**Issue by cscetbon** [aws-samples/aws-serverless-saas-workshop#61]
[Here](https://catalog.us-east-1.prod.workshops.aws/workshops/b0c6ad36-0a4b-45d8-856b-8a64f0ac76bb/en-US/lab6/71-architecture#pass-the-api-key-as-part-of-the-lambda-authorizer-authorization-response) the SAAS Workshop says that authentication can be done using an API Key or a lambda authorizer. Let's say I have an API Gateway the acts as a proxy to an AWS Service like a Firehose Delivery Stream, and that I want users of that API Gateway to go to the corresponding stream based on their tenant tiers. If I distribute API Keys to those tenants it seems there is no way to update the stream name on the fly because the lambda authorizer would not kick in and nothing would allow me to add this information to the context. If I were using a lambda authorizer I would be able to update the context with the corresponding stream, and in request template to use that to set the target stream name. Am I correct ? So how would you do that ? Not use API Keys but JWTs instead ? if yes how ? another solution ?

By the way it would be great to allow discussions to separate questions from issues on your repository 😉

**Comment by suhussai** [comment]
Hi @cscetbon , I think there's a misunderstanding here regarding API keys. If you look at this https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-api-key-source.html, it shows how the API keys can be sourced either from the headers or from the authorizer.

So, one option is to use an authorizer to set both the API key (based on the `tier` claim in the JWT, perhaps) and the stream.

**Comment by cscetbon** [comment]
@suhussai The issue with my case is that I don't have users, so it wouldn't be interacting with a Cognito User Pool getting a JWT token containing the tenant id information to get the API Key etc...

I need a way to distribute tokens or keys to authenticate with API Gateway and it doesn't seem I can use a JWT that doesn't expire, right ? Let's say I'm talking about a mobile app that is built and distributed to a specific tenant each time it's built with the right token/key. So in the case I described do you see another way than using an API Key ?

**Comment by suhussai** [comment]
@cscetbon , so are you using API Keys just for authorizing access from your mobile app to your API GW?

Have you looked at using a request parameter-based lambda authorizer? Using that, you can verify certain attributes (like the key you distributed) in the incoming request, and use that to authorize incoming requests. Here's an example: https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-use-lambda-authorizer.html#api-gateway-lambda-authorizer-request-lambda-function-create

You can also use that lambda authorizer to specify the appropriate stream based on the tenant tier (which I assume you're determining from the API Key in the request). Does that make sense?

**Comment by cscetbon** [comment]
>  a request parameter-based lambda authorizer?

Nope, I knew about a lambda authorizer in general but not on a request basis. I had in mind to use a lambda authorizer but wanted to use API Key to be able to specify usage plans and avoid extra cost by adding a lambda. It seems I won't have the choice here.

**Comment by suhussai** [comment]
> It seems I won't have the choice here.

Can you elaborate on this? Were you looking to build this solution (throttling via usage plans + setting custom stream based on API Key) without a lambda?

**Comment by cscetbon** [comment]
> Were you looking to build this solution (throttling via usage plans + setting custom stream based on API Key) without a lambda?

Yeah I thought there was a way somehow to do it using mapping transformation that could interact with a service to get the corresponding stream name, but maybe I was too hopeful 😬

**Comment by suhussai** [comment]
Ok, I think I get it.

How are the mobile apps indicating which tier they belong to? Are you determining that from the API Key that is passed in? What happens if an app belonging to one tier passes in an API Key belonging to a different tier?

**Comment by cscetbon** [comment]
> Are you determining that from the API Key that is passed in? What happens if an app belonging to one tier passes in an API Key belonging to a different tier?

The app doesn't exist yet and I'm more at a designing phase. Right now I was excepting to have a mapping of those keys somewhere, could be a secret in SSM or anything, that's why I was thinking that maybe mapping templates support accessing a secret and extract the corresponding stream name directly from there.

At first I was thinking of having a JWT with the information inside but then I realized I couldn't cause I don't want to have to renew those etc... So I was only thinking of having an API Key, but potentially if I was using an authorizer (which I'd like to avoid if possible to avoid extra cost and latency like I said) I could have a compound key made up of the key and a hash of the stream name for instance.

**Comment by suhussai** [comment]
One option is to enable caching on the authorizer. That should reduce costs and the hit to latency: https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-use-lambda-authorizer.html

I'll go ahead and close this out, but feel free to open if you still have questions. Thanks 👍
