### ISSUE TITLE
[Question] check changes with SAM when using nested stacks

### ISSUE THREAD

**Issue by cscetbon** [aws-samples/aws-serverless-saas-workshop#62]
I see you use SAM to deploy nested stacks but I just realized that it shows changes in the root stack but not in its nested stacks when you want to verify what changes you are to apply. It seems to be a real bummer, do you have any recommendations or advices regarding this issue ?

**Comment by ujwalbukka** [comment]
@cscetbon - Have you tried using [change sets for nested stacks](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/change-sets-for-nested-stacks.html). It looks like this might help you with your issue here.

**Comment by ujwalbukka** [comment]
Closing the issue. Please feel free to re-open it if you still have questions/issues
