### ISSUE TITLE
Not an issue just a clarification

### ISSUE THREAD

**Issue by raffaellanz** [aws-samples/aws-serverless-saas-workshop#63]
Great project and workshop.

Jus a couple of questions:

- this version seems. a bit different from the one the workshop refers to (e.g. https://github.com/aws-samples/aws-saas-factory-ref-solution-serverless-saas). What are the main difference?

- if I wanted to use this version as a starting point for a project what would be the files to use and and what would the scripts look like? This version seems more modular and flexible

- lastly the client side use a very date version of Angular. Is there a more up to date version and would you still recommend to use Angular? Thanks

**Comment by ujwalbukka** [comment]
Hi @raffaellanz 

1. You can compare the serverless saas reference solution [pre-requisites.sh](https://github.com/aws-samples/aws-saas-factory-ref-solution-serverless-saas/blob/main/Cloud9Setup/pre-requisites.sh)  and serverless saas workshop [pre-requisites.sh](https://github.com/aws-samples/aws-serverless-saas-workshop/blob/main/Cloud9Setup/pre-requisites.sh) to find the differences in the versions. Primarily the node, sam cli and cdk cli versions are  different. 
2. Not sure, what specific modules/components versions are you referring to but as mentioned above the pre-requisites.sh script will have all the pre-requisite modules. And project specific modules can be found in the project package.json. But we recommend to use the latest versions as a starting point.
3. Our client side code is very minimal just to showcase solution functionality and it is not production ready code. There are lot of widely popular UI frameworks like React, Angular, Vue.js ...etc. Would suggest to pick one which best suites your use cases and/or requirements.

**Comment by ujwalbukka** [comment]
Closing the issue. Please feel free to re-open it if you still have questions/issues
