### ISSUE TITLE
Invalid Python-version

### ISSUE THREAD

**Issue by MarcusMiss** [aws-samples/aws-serverless-saas-workshop#8]
After executing script _./pre-requisites.sh_ the validation-script _./pre-requisites-versions-check.sh_ was complaining about wrong python-version (3.7.x instead of 3.8.x).
I think problem is in script  _./pre-requisites.sh_: the alternatives invocation is not valid.
Instead of 
_sudo alternatives --install /usr/bin/python3 python3 /usr/bin/python3.8_
it should be
_sudo alternatives --install /usr/bin/python3 python3 /usr/bin/python3.8 **1**_

**Comment by ujwalbukka** [comment]
Hi @MarcusMiss - Thanks for pointing this error, we have fixed it. Please pull latest repo.
I will close this issue, if you still see issues please feel free to open it.
