### ISSUE TITLE
Lab 3 - Adding Product Creates Error

### ISSUE THREAD

**Issue by ccantrell72** [aws-samples/aws-serverless-saas-workshop#9]
When creating a product, I get this error.  [object Object]

**Comment by suhussai** [comment]
Hi @ccantrell72,

Thanks for reporting this issue. I'll run the Lab again on my end to see if I can replicate the issue. In the meantime, would you be able to provide more information on the error you are seeing? It might help to review the appropriate Log Group in CloudWatch to see if the error is being logged there.

**Comment by suhussai** [comment]
I tried replicating the issue by doing the following, but I was able to create the product without errors:

1. Deployed labs 2 and 3 using the solution provided
2. Created a basic tenant via the admin portal
3. Logged in as the basic tenant after receiving instructions via email
4. Created a new product, and I could see the newly created product in the list of products

When convenient, would you be able to list out the steps that led to the error above?

**Comment by ujwalbukka** [comment]
Closing this issue. Please re-open if you still have issues.
